language: php
php:
  - 7.2
before_script:
  - composer self-update
  - composer install --no-interaction
script:
  - vendor/bin/phpunit
  - ./vendor/bin/phpcs --ignore=vendor,bootstrap/cache/,storage .
