language: php
php:
  - 7.4
before_script:
  - composer self-update
  - composer install
  - chmod +x pre-commit.sh
script:
#  - ./vendor/bin/phpcs --ignore=vendor,bootstrap/cache/,storage .
#  - ./vendor/bin/phpcbf --ignore=vendor,bootstrap/cache/,storage .
#  - ./vendor/bin/phpcs --ignore=vendor,bootstrap/cache/,storage -p app/
  - ./pre-commit-2.sh
#  - ./vendor/bin/phpcs --ignore=vendor,bootstrap/cache/,storage --standard=PSR2 --encoding=utf-8 -n -p .
