language: php
php:
  - 7.4
before_script:
  - composer self-update
  - composer install
script:
#  - ./vendor/bin/phpcs --ignore=vendor,bootstrap/cache/,storage .
#  - ./vendor/bin/phpcbf --ignore=vendor,bootstrap/cache/,storage .
  - ./vendor/bin/phpcs --ignore=vendor,bootstrap/cache/,storage -p .d
